---
# tasks file for roles/osp-instance-delete
#  - name: Fetch Instance Info
  - name: Delete instances
    os_server:
      cloud:            "{{ openstack_cloud                           | default('openstack') }}"
      name:             "{{ __openstack_server.name }}"
      state:            absent
    loop: "{{ openstack_servers }}"
    loop_control:
      loop_var: __openstack_server
    async: 900
    poll: 0
    register: r_instances
