---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable base repos
  yum_repository:
    name: "Red Hat Enterprise Linux 7"
    enabled: 1
    baseurl: "http://192.168.0.5/repos/rhel-7-server-rpms"
    gpgcheck: 0

- name: enable common repos
  yum_repository:
    name: "Red Hat Enterprise Linux 7 Common"
    enabled: 1
    baseurl: "http://192.168.0.5/repos/rhel-7-server-rh-common-rpms"
    gpgcheck: 0

- name: enable extra repos
  yum_repository:
    name: "Red Hat Enterprise Linux 7 Extras"
    enabled: 1
    baseurl: "http://192.168.0.5/repos/rhel-7-server-extras-rpms"
    gpgcheck: 0

- name: enable optional repos
  yum_repository:
    name: "Red Hat Enterprise Linux 7 Optional"
    enabled: 1
    baseurl: "http://192.168.0.5/repos/rhel-7-server-optional-rpms"
    gpgcheck: 0
 
#- name: install base tools and packages

